### ISSUE TITLE
Sleep less in the manager

### ISSUE THREAD

**Issue by Art3miX** [timewave-computer/valence-protocol#50]
Currently we sleep over a constant 12 seconds after each execute or instantiation message we execute on the chain.
We want to sleep as less as possible, like @keyleu suggested we can query the hash and see when its on chain, and loop over it every seconds, so instead of waiting always 12 seconds, we wait the minimum needed.

**Comment by stiiifff** [comment]
I think the correct pattern would be to use a wait handle to block the current thread until either, the transaction is finalized or errors out (need to subscribe to chain events before broadcasting the tx .. I'm not sure what's the correct API for that), or there is a timeout of x seconds. Basically, you want to wait asynchronously until some events occur, not wait synchronously and poll for result.

**Comment by Art3miX** [comment]
The only thing we can fix if a tx fails is if the wallet is out of gas money, which will happen in rare cases.
any other errors will need a manual intervention, having a separate queue for chain txs, is nice to have, it will allow us to choose if we want to continue the current workflow init process or start a new one (in case the config is wrong which should be easily checked before doing txs).
I don't this is a priority right now, its a nice to have to give more insight and have some extra control, but won't actually fix anything.
